. $HOME/.shell_utils/aliases/system/directory.fish
. $HOME/.shell_utils/aliases/system/disks.fish
. $HOME/.shell_utils/aliases/system/display.fish
. $HOME/.shell_utils/aliases/system/kernel.fish
. $HOME/.shell_utils/aliases/system/pacman.fish
. $HOME/.shell_utils/aliases/system/pointer.fish
. $HOME/.shell_utils/aliases/system/ram.fish
. $HOME/.shell_utils/aliases/system/sensors.fish
. $HOME/.shell_utils/aliases/system/system.fish
. $HOME/.shell_utils/aliases/system/user.fish
. $HOME/.shell_utils/aliases/adb.fish
. $HOME/.shell_utils/aliases/beep.fish
. $HOME/.shell_utils/aliases/chatgpt_aliases.fish
. $HOME/.shell_utils/aliases/check_for_alias.fish
. $HOME/.shell_utils/aliases/coin.fish
. $HOME/.shell_utils/aliases/date.fish
. $HOME/.shell_utils/aliases/dictionaries.fish
. $HOME/.shell_utils/aliases/editors_vim_emacs.fish
. $HOME/.shell_utils/aliases/extract_files.fish
. $HOME/.shell_utils/aliases/ffmpeg.fish
. $HOME/.shell_utils/aliases/fonts.fish
. $HOME/.shell_utils/aliases/game.fish
. $HOME/.shell_utils/aliases/git.fish
. $HOME/.shell_utils/aliases/image_magick.fish
. $HOME/.shell_utils/aliases/inch.fish
. $HOME/.shell_utils/aliases/math.fish
. $HOME/.shell_utils/aliases/net.fish
. $HOME/.shell_utils/aliases/nvidia.fish
. $HOME/.shell_utils/aliases/ocr.fish
. $HOME/.shell_utils/aliases/pdf.fish
. $HOME/.shell_utils/aliases/pictures.fish
. $HOME/.shell_utils/aliases/pip.fish
. $HOME/.shell_utils/aliases/py.fish
. $HOME/.shell_utils/aliases/rename_cases.fish
. $HOME/.shell_utils/aliases/tiff.fish
. $HOME/.shell_utils/aliases/translation.fish
. $HOME/.shell_utils/aliases/typescripting.fish
. $HOME/.shell_utils/aliases/video.fish
. $HOME/.shell_utils/aliases/vnc_ssh_telnet_servers.fish
. $HOME/.shell_utils/aliases/waydroid.fish
. $HOME/.shell_utils/aliases/webcam.fish
. $HOME/.shell_utils/aliases/helps.fish
. $HOME/.shell_utils/aliases/files.fish
. $HOME/.shell_utils/aliases/for_scripts.fish
. $HOME/.shell_utils/aliases/ls.fish
. $HOME/.shell_utils/aliases/freds_aliases.fish
. $HOME/.shell_utils/aliases/shell_utils.fish
