. "${HOME}"/.shell_utils/aliases/adb.sh
. "${HOME}"/.shell_utils/aliases/cd.sh
. "${HOME}"/.shell_utils/aliases/chatgpt_aliases.sh
. "${HOME}"/.shell_utils/aliases/check_for_alias.sh
. "${HOME}"/.shell_utils/aliases/coin.sh
. "${HOME}"/.shell_utils/aliases/date.sh
. "${HOME}"/.shell_utils/aliases/dictionaries.sh
. "${HOME}"/.shell_utils/aliases/editors_vim_emacs.sh
. "${HOME}"/.shell_utils/aliases/extract_files.sh
. "${HOME}"/.shell_utils/aliases/ffmpeg.sh
. "${HOME}"/.shell_utils/aliases/files.sh
. "${HOME}"/.shell_utils/aliases/fonts.sh
. "${HOME}"/.shell_utils/aliases/for_scripts.sh
. "${HOME}"/.shell_utils/aliases/freds_aliases.sh
. "${HOME}"/.shell_utils/aliases/game.sh
. "${HOME}"/.shell_utils/aliases/git.sh
. "${HOME}"/.shell_utils/aliases/helps.sh
. "${HOME}"/.shell_utils/aliases/image_magick.sh
. "${HOME}"/.shell_utils/aliases/inch.sh
. "${HOME}"/.shell_utils/aliases/ls.sh
. "${HOME}"/.shell_utils/aliases/math.sh
. "${HOME}"/.shell_utils/aliases/net.sh
. "${HOME}"/.shell_utils/aliases/nvidia.sh
. "${HOME}"/.shell_utils/aliases/ocr.sh
. "${HOME}"/.shell_utils/aliases/pdf.sh
. "${HOME}"/.shell_utils/aliases/pictures.sh
. "${HOME}"/.shell_utils/aliases/pip.sh
. "${HOME}"/.shell_utils/aliases/py.sh
. "${HOME}"/.shell_utils/aliases/rename_cases.sh
. "${HOME}"/.shell_utils/aliases/shell_utils.sh
. "${HOME}"/.shell_utils/aliases/system/directory.sh
. "${HOME}"/.shell_utils/aliases/system/disks.sh
. "${HOME}"/.shell_utils/aliases/system/display.sh
. "${HOME}"/.shell_utils/aliases/system/kernel.sh
. "${HOME}"/.shell_utils/aliases/system/pacman.sh
. "${HOME}"/.shell_utils/aliases/system/pointer.sh
. "${HOME}"/.shell_utils/aliases/system/ram.sh
. "${HOME}"/.shell_utils/aliases/system/sensors.sh
. "${HOME}"/.shell_utils/aliases/system/system.sh
. "${HOME}"/.shell_utils/aliases/system/user.sh
. "${HOME}"/.shell_utils/aliases/tiff.sh
. "${HOME}"/.shell_utils/aliases/translation.sh
. "${HOME}"/.shell_utils/aliases/typescripting.sh
. "${HOME}"/.shell_utils/aliases/video.sh
. "${HOME}"/.shell_utils/aliases/vnc_ssh_telnet_servers.sh
. "${HOME}"/.shell_utils/aliases/waydroid.sh
. "${HOME}"/.shell_utils/aliases/webcam.sh
