source $HOME/.shell_utils/aliases/adb.fish
source $HOME/.shell_utils/aliases/chatgpt_aliases.fish
source $HOME/.shell_utils/aliases/check_for_alias.fish
source $HOME/.shell_utils/aliases/coin.fish
source $HOME/.shell_utils/aliases/date.fish
source $HOME/.shell_utils/aliases/dictionaries.fish
source $HOME/.shell_utils/aliases/editors_vim_emacs.fish
source $HOME/.shell_utils/aliases/extract_files.fish
source $HOME/.shell_utils/aliases/ffmpeg.fish
source $HOME/.shell_utils/aliases/files.fish
source $HOME/.shell_utils/aliases/fonts.fish
source $HOME/.shell_utils/aliases/for_scripts.fish
source $HOME/.shell_utils/aliases/freds_aliases.fish
source $HOME/.shell_utils/aliases/game.fish
source $HOME/.shell_utils/aliases/git.fish
source $HOME/.shell_utils/aliases/image_magick.fish
source $HOME/.shell_utils/aliases/inch.fish
source $HOME/.shell_utils/aliases/ls.fish
source $HOME/.shell_utils/aliases/math.fish
source $HOME/.shell_utils/aliases/net.fish
source $HOME/.shell_utils/aliases/nvidia.fish
source $HOME/.shell_utils/aliases/ocr.fish
source $HOME/.shell_utils/aliases/pdf.fish
source $HOME/.shell_utils/aliases/pictures.fish
source $HOME/.shell_utils/aliases/pip.fish
source $HOME/.shell_utils/aliases/py.fish
source $HOME/.shell_utils/aliases/rename_cases.fish
source $HOME/.shell_utils/aliases/shell_utils.fish
source $HOME/.shell_utils/aliases/system/directory.fish
source $HOME/.shell_utils/aliases/system/disks.fish
source $HOME/.shell_utils/aliases/system/display.fish
source $HOME/.shell_utils/aliases/system/kernel.fish
source $HOME/.shell_utils/aliases/system/pacman.fish
source $HOME/.shell_utils/aliases/system/pointer.fish
source $HOME/.shell_utils/aliases/system/ram.fish
source $HOME/.shell_utils/aliases/system/sensors.fish
source $HOME/.shell_utils/aliases/system/system.fish
source $HOME/.shell_utils/aliases/system/user.fish
source $HOME/.shell_utils/aliases/tiff.fish
source $HOME/.shell_utils/aliases/translation.fish
source $HOME/.shell_utils/aliases/typescripting.fish
source $HOME/.shell_utils/aliases/video.fish
source $HOME/.shell_utils/aliases/vnc_ssh_telnet_servers.fish
source $HOME/.shell_utils/aliases/waydroid.fish
source $HOME/.shell_utils/aliases/webcam.fish
source $HOME/.shell_utils/aliases/helps.fish
