#!/usr/bin/env bash
# License: GPLv3
# Credits: Felipe Facundes

: <<'DOCUMENTATION'
Creates a new file with execution permission and opens it in VS Code or VSCodium, ensuring one of them is installed.
DOCUMENTATION

file="$1"

[[ -z "$file" ]] && echo "Usage: ${0##*/} new_file" && exit 1
[[ -f "$file" ]] && [[ ! -x "$file" ]] && echo 'File is not executable!'

if ! command -v code &>/dev/null && ! command -v codium &>/dev/null; then
    echo 'Install code or codium, then run this script again.'
    exit 1
fi

if command -v codium &>/dev/null; then
    mycode=$(command -v codium)
else
    mycode=$(command -v code)
fi

# If you are creating a new file, it will already be generated with permissions
[[ ! -f "$file" ]] && touch "$file" && [[ ! -x "$file" ]] && chmod +x "$file"
# If the file exists, permissions will only be given if the file has a shebang
if grep -q "^#!" "$file"; then
    [[ ! -x "$file" ]] && chmod +x "$file"
fi
"$mycode" "$file"
