#!/usr/bin/env bash

clear

# Color definitions
color_yellow_bold="\e[1;33m"
color_white_bold="\e[1;37m"
color_red_bold="\e[1;31m"
color_reset="\e[0m"

lock_file="/var/lib/pacman/db.lck"
pid_pacman=$(pidof pacman)

# Associative array to store messages in both languages
declare -A MESSAGES

if [[ "${LANG,,}" =~ pt_ ]]; then
    MESSAGES=(
        [lock_exists]="O arquivo de bloqueio está presente:"
        [pacman_running]="O Pacman está em execução, conforme PID:"
        [pacman_not_active]="O Pacman (Gerenciador de Pacotes do Arch Linux) não está ativo."
        [lock_not_present]="O arquivo de bloqueio NÃO está presente!"
        [pacman_not_running]="O Pacman não está em execução!"
        [exiting]="Encerrando..."
    )
else
    MESSAGES=(
        [lock_exists]="The lock file is present:"
        [pacman_running]="Pacman is running, according to PID:"
        [pacman_not_active]="Pacman (Arch Linux Package Manager) is not active."
        [lock_not_present]="The lock file is NOT present!"
        [pacman_not_running]="Pacman is not running!"
        [exiting]="Exiting..."
    )
fi

if [[ -f "$lock_file" ]]; then
    echo -e "${color_yellow_bold} ${MESSAGES[lock_exists]} ${color_white_bold} $lock_file $color_reset"
fi

if [[ -n "$pid_pacman" ]]; then
    echo -e "${color_yellow_bold} ${MESSAGES[pacman_running]} ${color_white_bold} $pid_pacman $color_reset"
    exit 0
fi

if [[ ! -f "$lock_file" && -z "$pid_pacman" ]]; then
    echo -e "${color_red_bold} ${MESSAGES[pacman_not_active]} $color_reset"
    echo -e "${color_red_bold} ${MESSAGES[exiting]} $color_reset"
    exit 1
else
    if [[ ! -f "$lock_file" ]]; then
        echo -e "${color_red_bold} ${MESSAGES[lock_not_present]} $color_reset"
    fi

    if [[ -z "$pid_pacman" ]]; then
        echo -e "${color_red_bold} ${MESSAGES[pacman_not_running]} $color_reset"
        echo -e "${color_red_bold} ${MESSAGES[exiting]} $color_reset"
        exit 1
    fi
fi