#!/usr/bin/env bash
# License: GPLv3
# Credits: Felipe Facundes

if mount | grep Public/Android >/dev/null; then 
	sudo umount -R ~/Public/Android || { echo "Close the terminal or file manager open in ~/Public/Android" && exit 1; }
fi
sudo systemctl stop waydroid-container.service
sudo waydroid session stop && sudo waydroid container stop
