# https://github.com/mpv-player/mpv/issues/4494
# https://mpv.io/manual/master/
input-ipc-server=/tmp/mpvsocket

geometry=30%
#fs
video-aspect-override=16/9
sub-color="#33FFFF"
#sub-font="Ubuntu"
sub-font="Poppins"
sub-auto=fuzzy
sub-fix-timing=yes
blend-subtitles=yes
alang=pt,por
slang=por,pt
save-position-on-quit

# global (default) options
#loop-playlist=inf
#loop-file=inf
#loop-playlist=no
#loop-file=no

#osc=no

vo=gpu #x11 #xv
gpu-api=opengl  # Use somente se vo=gpu PARA gpu-api use opengl ou vaapi, vulkan EXEMPLO: gpu-api=opengl

#hwdec=no # Para forçar o uso de CPU
hwdec=auto
#profile=gpu-hq
keepaspect=no
cursor-autohide=200
#audio-file-auto=fuzzy # external audio doesn't has to match the file name exactly to autoload
#volume-max=200 # maximum volume in %, everything above 100 results in amplification
volume=100 # default volume, 100 = unchanged
audio-pitch-correction=yes # automatically scale tempo when playing with different speed
audio-channels=2
gapless-audio=yes
no-border
ontop=yes
image-display-duration=inf
terminal=yes
force-window=no
idle=once
player-operation-mode=pseudo-gui
screenshot-directory=~/Videos/Capture
screenshot-format=jpg

user-agent="Mozilla/5.0"
# --- 1080p
ytdl-format="((bestvideo[height<=?1080]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
#ytdl-format="((bestvideo[vcodec^=vp9][height<=?1080]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
# --- 720p
#ytdl-format="((bestvideo[height<=?720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
