# Defining environmental variables
set -gx GO111MODULE ""
set -gx GOARCH "amd64"
set -gx GOBIN ""
set -gx GOCACHE "$HOME/.cache/go-build"
set -gx GOENV "$HOME/.config/go/env"
set -gx GOEXE ""
set -gx GOEXPERIMENT ""
set -gx GOFLAGS ""
set -gx GOHOSTARCH "amd64"
set -gx GOHOSTOS "linux"
set -gx GOINSECURE ""
set -gx GOMODCACHE "$HOME/.go/pkg/mod"
set -gx GONOPROXY ""
set -gx GONOSUMDB ""
set -gx GOOS "linux"
set -gx GOPATH "$HOME/.go"
set -gx GOPRIVATE ""
set -gx GOPROXY "https://proxy.golang.org,direct"
set -gx GOROOT "/usr/lib/go"
set -gx GOSUMDB "sum.golang.org"
set -gx GOTMPDIR ""
set -gx GOTOOLDIR "/usr/lib/go/pkg/tool/linux_amd64"
set -gx GOVCS ""
# set -gx GOVERSION "go1.20.3"
set -gx GCCGO "gccgo"
set -gx GOAMD64 "v1"
set -gx AR "ar"
set -gx CC "gcc"
set -gx CXX "g++"
set -gx CGO_ENABLED "1"
set -gx GOMOD "/dev/null"
set -gx GOWORK ""
set -gx CGO_CFLAGS "-O2 -g"
set -gx CGO_CPPFLAGS ""
set -gx CGO_CXXFLAGS "-O2 -g"
set -gx CGO_FFLAGS "-O2 -g"
set -gx CGO_LDFLAGS "-O2 -g"
set -gx PKG_CONFIG "pkg-config"
set -gx GOGCCFLAGS "-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3413824791=/tmp/go-build -gno-record-gcc-switches"