# chronometers
alias chronometer='~/.shell_utils/scripts/chronometer.sh -m1'
alias stopwatch='chronometer'
alias chron='chronometer'
alias cronometro='chronometer'
alias chronometer2='~/.shell_utils/scripts/chronometer.sh -m2'
alias stopwatch2='chronometer2'
alias chron2='chronometer2'
alias cronometro2='chronometer2'
alias chronometer3='~/.shell_utils/scripts/chronometer.sh -m3'
alias stopwatch3='chronometer3'
alias chron3='chronometer3'
alias cronometro3='chronometer3'