alias remove_extension='help remove_extension'
alias recent_files='help recent_files'

alias file_type='~/.shell_utils/scripts/test_file_type'
alias test_file='file_type'

alias has_audio='~/.shell_utils/scripts/audio_exists_here'
alias have_audio='has_audio'
alias is_audio='has_audio'
alias audio_here='has_audio'
alias has_video='~/.shell_utils/scripts/video_exists_here'
alias have_video='has_video'
alias is_video='has_video'
alias video_here='has_video'
alias has_image='~/.shell_utils/scripts/image_exists_here'
alias have_image='has_image'
alias is_image='has_image'
alias image_here='has_image'
alias has_pdf='~/.shell_utils/scripts/pdf_exists_here'
alias have_pdf='pdf_exists_here'
alias is_pdf='pdf_exists_here'
alias pdf_here='pdf_exists_here'

alias mime='help default_mime'
alias default_mime='mime'