alias markdown_terminal_reader='help markdown_terminal_reader'
alias abnt_tcc='help abnt_tcc'
alias sed_man='help sed_man'
alias sed_info='help sed_info'
alias sed_help='help sed_help'

alias trap_signals='help trap_signals'
alias trap_signals_a_help='trap_signals'
alias trap_signals_a_comprehensive_guide='trap_signals'
alias trap_signals_en='printf "1\n" | trap_signals'
alias trap_signals_pt='printf "2\n" | trap_signals'

alias aur_new_package='help aur_new_package'
alias aur_new_package_en='printf "1\n" | aur_new_package'
alias aur_new_package_pt='printf "2\n" | aur_new_package'
alias aur_new_package_es='printf "3\n" | aur_new_package'