alias pdf_encrypt_decrypt_help="helps encrypt_decrypt_pdf"
alias ghostscript_settings_vectorDevices_help="helps ghostscript_vectorDevices"
alias pdf_ghostscript_settings_vectorDevices_help="helps ghostscript_vectorDevices"
alias pdf_metadata_help="helps pdf_metadata"