#####################################################
################# Pictures / Photos #################
alias pdf2text='~/.shell_utils/scripts/faqs/pdftotext-help'
alias ascii_image_converter_help='echo https://github.com/TheZoraiz/ascii-image-converter'
alias ascii_image_converter_man='ascii_image_converter_help'
alias convert='help im_options; magick'
alias texttopdf_help='help texttopdf_help'
alias text2pdf='texttopdf_help'
alias lesspipe='lesspipe.sh'
alias pdfimg='help pdfimg'
alias pdftoimg='pdfimg; pdftoppm'
alias pdftoppm='pdfimg; pdftoppm'
alias pic_dir="cd ~/Pictures"
alias wpp="cd ~/Pictures/Wallpapers"
alias wallpp="wpp"
alias resolutions='help resolutions'
alias sizes='resolutions'
alias mi='~/.shell_utils/scripts/enhanced-image'
alias improve_image='mi'
alias melhorar_imagem='mi'
alias rs='mi'
alias resize='mi'
alias 4k='~/.shell_utils/scripts/4k 4k'
alias 4kj-m='~/.shell_utils/scripts/4k 4kj-m'
alias 4kp-m='~/.shell_utils/scripts/4k 4kp-m'
alias 4kw-m='~/.shell_utils/scripts/4k 4kw-m'
alias 4kj='~/.shell_utils/scripts/4k 4kj'
alias 4kp='~/.shell_utils/scripts/4k 4kp'
alias 4kw='~/.shell_utils/scripts/4k 4kw'
alias ulight='~/.shell_utils/scripts/imagemagick-functions-and-help ulight'
alias ulight-m='~/.shell_utils/scripts/imagemagick-functions-and-help ulight-m'
alias light-hight='~/.shell_utils/scripts/imagemagick-functions-and-help ulight'
alias light-hight-m='~/.shell_utils/scripts/imagemagick-functions-and-help ulight-m'
alias negative-black='~/.shell_utils/scripts/imagemagick-functions-and-help negative-black'
alias negative-black-m='~/.shell_utils/scripts/imagemagick-functions-and-help negative-black-m'
alias contrast-dark='~/.shell_utils/scripts/imagemagick-functions-and-help contrast-dark'
alias contrast-dark-m='~/.shell_utils/scripts/imagemagick-functions-and-help contrast-dark-m'
alias remaster_tips='~/.shell_utils/scripts/imagemagick-functions-and-help remaster_tips'
alias remasterizar_dicas='remaster_tips'
alias realce_dicas='remaster_tips'
alias realcar_dicas='remaster_tips'
alias enhancer_tips='remaster_tips'
alias remaster='~/.shell_utils/scripts/imagemagick-functions-and-help remaster'
alias enhancer='remaster'
alias remasterizar='remaster'
alias realce='remaster'
alias realcar='remaster'
# https://stackoverflow.com/questions/26889358/generate-color-palette-from-image-with-imagemagic
# https://www.imagemagick.org/discourse-server/viewtopic.php?t=2896
alias cor-dominant='~/.shell_utils/scripts/imagemagick-functions-and-help color-dominant'
alias cor-dominant2='~/.shell_utils/scripts/imagemagick-functions-and-help color-dominant2'
alias cor2pallete='~/.shell_utils/scripts/imagemagick-functions-and-help cor2pallete'
alias pallete='cor2pallete'
alias paleta='pallete'
# https://imagemagick.org/discourse-server/viewtopic.php?t=31416
# https://graphicdesign.stackexchange.com/questions/28561/how-can-i-achieve-this-cartoon-effect
# http://mariovalle.name/postprocessing/ImageTools.html
# https://askubuntu.com/questions/703184/how-to-transform-an-image-into-a-cartoon-from-command-line
# http://www.fmwconcepts.com/imagemagick/cartoon/
# https://stackoverflow.com/questions/47017741/image-filter-to-cartoonize-and-colorize
alias cartoonize='~/.shell_utils/scripts/cartoonize cartoonize'
alias cartoonize2='~/.shell_utils/scripts/cartoonize cartoonize2'
alias cartoonize3='~/.shell_utils/scripts/cartoonize cartoonize3'
alias cartoonize4='~/.shell_utils/scripts/cartoonize cartoonize4'
alias cartoonize4-other-method='~/.shell_utils/scripts/cartoonize cartoonize4-other-method'
alias cartoonize5='~/.shell_utils/scripts/cartoonize cartoonize5'
alias cartoonize6='~/.shell_utils/scripts/cartoonize cartoonize6'
alias cartoonize6-remover-espinhas='~/.shell_utils/scripts/cartoonize cartoonize5'
alias cartoonize7='~/.shell_utils/scripts/cartoonize cartoonize7'
alias cartoonize8='~/.shell_utils/scripts/cartoonize cartoonize8'
#alias catimg='viu'