alias pip_upgrade='~/.shell_utils/scripts/pip-upgrade'
alias pip_upgrade_all='pip_upgrade pip_upgrade_all'
alias pip_upgrade_all_local='pip_upgrade pip_upgrade_all_local'
alias pip_upgrade_all_2='pip_upgrade pip_upgrade_all_2'
alias pip_upgrade_all_2_local='pip_upgrade pip_upgrade_all_2_local'
