alias md5sum_dir='~/.shell_utils/scripts/md5sum_directory'
alias dir_md5sum='md5sum_dir'
alias directory_md5sum='md5sum_dir'
alias md5sum_of_all_files_in_a_directory='md5sum_dir'
alias md5sum_of_all_files_in_a_dir='md5sum_dir'
alias md5sum_directory='md5sum_dir'
alias hash_dir='md5sum_dir'
alias hash_directory='md5sum_dir'