#!/usr/bin/env bash
# License: GPLv3
# Credits: Felipe Facundes


: <<'DOCUMENTATION'
This Bash script is designed to manage and display a list of books stored in a specified directory, allowing users to read them in various formats.

Purpose:
The script provides a user-friendly interface for selecting and reading books in formats such as PDF, TXT, and EPUB.

Strengths:
1. Format Support: Handles multiple book formats (PDF, TXT, EPUB).
2. User  Interaction: Prompts users to select a book by number, enhancing usability.
3. Error Handling: Includes checks for valid input and format recognition.
4. Temporary File Management: Converts PDF files to text for easier reading.
5. Clear Output: Uses 'less' for paginated viewing of book content.

Capabilities:
- Lists available books in the specified directory.
- Reads and displays the content of selected books based on their format.
- Provides a clean exit option for users.
DOCUMENTATION

# Capture Ctrl+C and end children processes
trap '(kill -TERM -- -$$) &>/dev/null' SIGINT SIGTERM SIGHUP SIGQUIT

clear

SCRIPT="${0##*/}"
TMPDIR="${TMPDIR:-/tmp}"
TMPBOOKDIR="${TMPDIR}/${SCRIPT%.*}"
XDG_DOCUMENTS_DIR=${XDG_DOCUMENTS_DIR:-$(xdg-user-dir DOCUMENTS 2>/dev/null || echo "$HOME/Documents")}

# Setting the eBook folders
news_books="$1"
books_folder="${HOME}/.shell_utils/books"
xdg_books_folder="${XDG_DOCUMENTS_DIR}/Books"

[[ -d "${TMPBOOKDIR}" ]] && rm -rf "${TMPBOOKDIR}"
[[ ! -d "${TMPBOOKDIR}" ]] && mkdir -p "${TMPBOOKDIR}"
[[ ! -d "${xdg_books_folder}" ]] && mkdir -p "${xdg_books_folder}"

# Combining the two folders to get all ebooks
if [[ -d "$news_books" ]]; then
    books_list=("${news_books}"/*.* "${books_folder}"/*.* "${xdg_books_folder}"/*.*)
    shift
else
    books_list=("${books_folder}"/*.* "${xdg_books_folder}"/*.*)
    unset news_books
fi

for i in "${!books_list[@]}"; do
    declare -l ext_test="${books_list[$i]##*.}"
    declare -l ext_test="${ext_test,,}" # lowercase

    case $ext_test in 
        csv|xls|xlsx|rtf|doc|docx|odt|ods|odp|sxw|ppt|pptx|ipynb|epub|txt|md|markdown|pod|pdf|png|jpg|jpeg|djvu|postscript|ps|dvi|htm|html|xhtml|xml)
            continue
        ;;
        *)
            unset "books_list[$i]"
        ;;
    esac
done

books_list=("${books_list[@]}")

# ANSI color for highlighting the selected book
red="\033[1;31m"
highlight="\033[44;1;32m"  # Cyan background, bold green text
nc="\033[0m"  # Reset

cleanup() {
    [[ -d "${TMPBOOKDIR}" ]] && rm -rf "${TMPBOOKDIR}"
    reset
    clear
    exit 0
}
trap cleanup EXIT

# Function to display books list
display_books() {
    local list=()
    if [[ -n "$1" ]]; then
        list=("${filtered_books[@]}")
    else
        list=("${books_list[@]}")
    fi
    
    number=0
    for book in "${list[@]}"; do
        if [[ $number -eq $selected ]]; then
            echo -e "$highlight$number)    ${book}$nc"
        else
            echo -e "$number)    ${book}"
        fi
        ((number++)) || true
    done
}

_glow_no_kill() {
    local file="$1"
    env COLORTERM=8bit glow -p -s dark -- "$file" 2>/dev/null
    status=$? && [[ "$status" == 0 ]] && return 0
    [[ "$status" -gt 0 ]] && return 1
}

markdown_reader() {
    local file="$1"
    local mr="$HOME/.shell_utils/scripts/markdown_reader.sh"
    [[ -z "$BOOKS_MARKDOWN" || "$BOOKS_MARKDOWN" == 5 ]] && [[ -f "$mr" ]] &&
    "$mr" -nc -nf -- "$file" && return 0
    [[ -z "$BOOKS_MARKDOWN" || "$BOOKS_MARKDOWN" == 5 ]] && command -v markdown_reader.sh &>/dev/null &&
    markdown_reader.sh -nc -nf -- "$file" && return 0
    [[ -z "$BOOKS_MARKDOWN" || "$BOOKS_MARKDOWN" == 1 ]] && cmd_check glow glow &&
    _glow_no_kill "$file" && return 0
    [[ -z "$BOOKS_MARKDOWN" || "$BOOKS_MARKDOWN" == 2 ]] && cmd_check bat bat &&
    env COLORTERM=8bit bat --color=always --style="plain" -- "$file" && return 0
    [[ -z "$BOOKS_MARKDOWN" || "$BOOKS_MARKDOWN" == 3 ]] && cmd_check mdless mdless &&
    mdless -P -- "$file" && return 0
    [[ -z "$BOOKS_MARKDOWN" || "$BOOKS_MARKDOWN" == 4 ]] && cmd_check mdcat mdcat &&
    mdcat -- "$file" && return 0
    return 1
}

cmd_check() {
    [[ "${#no_cmd[*]}" -gt 1 ]] && msg=$(echo "${no_cmd[*]}" | awk 'BEGIN {first=1} {for (i=1; i<=NF; i++) \
    {if (first) {printf "%s", $i; first=0} else {printf " or %s", $i}}} END {print ""}') || msg="${no_cmd[*]}"
    [[ "$1" == "-msg" ]] && printf '\e7\e[K%s\e8' "Install $msg" && no_cmd=() && exit 1
    ! command -v "$1" 1>/dev/null && no_cmd+=(\""$2"\") && return 1 || return 0
}

less_pid() {
    less -S -R -i &
    less_pid=$!
    wait "$less_pid" 
    return 0
}

margin() {
    local file="$1"
    { cmd_check fold coreutils && cmd_check less less; } || cmd_check -msg
    fold -s -w $(($(tput cols) - ${BOOKS_MARGIN:-5})) "$file" | less_pid && return 0
}

any_file() {
    file="$1"
    file "$file" | sed -n 's/.*:\s*\(.*\)/\1/p' && echo &&
    strings -n 10 "$file" 2>/dev/null | sed '/^[0-9]\{11\}/d' && return 0
}

office_convert() {
    local file="$1"
    local temp_dir="${TMPBOOKDIR}/temp_book"
    local temp_file="${TMPBOOKDIR}/temp_file.md"
    [[ -f "${temp_file}" ]] && rm -f "${temp_file}"
    [[ -d "${temp_dir}" ]] && rm -rf "${temp_dir}"

    case "${ext_test}" in
        csv)
            { cmd_check csvtable csvtable && csvtable "$file" | less_pid && return 0; } ||
            { cmd_check csvlook csvlook && csvlook -S "$file" | less_pid && return 0; } ||
            { awk -F, '{ printf "%-20s %-20s %-20s\n", $1, $2, $3 }' "$file" | less_pid && return 0; } ||
            column -t -s, "$file" | less_pid && return 0
            ;;
        xlsx)
            { cmd_check xlsx2csv xlsx2csv && xlsx2csv -- "$file" | less_pid && return 0; } ||
            cmd_check xlscat xlscat && xlscat -L -R all "$file" | less_pid && return 0
            ;;
        rtf)
            { cmd_check catdoc catdoc && margin <(catdoc -- "$file") && return 0; } ||
            cmd_check unrtf unrtf && margin <(unrtf --text "$file") && return 0
            ;;
        doc)
            cmd_check antiword antiword && margin <(antiword "$file") && return 0
            ;;
        docx)
            cmd_check docx2txt docx2txt && margin <(docx2txt "$file" - 2>/dev/null) && return 0
            ;;
        odt|ods|odp|sxw)
            { cmd_check odt2txt odt2txt && margin <(odt2txt "$file") && return 0; } ||
            [[ "${ext_test}" =~ ^sxw ]] && cmd_check sxw2txt sxw2txt && margin <(sxw2txt "$file") && return 0
            ;;
        pptx)
            cmd_check pptx2md pptx2md && pptx2md --disable-image --disable-wmf -o "$temp_file" "$file" &&
            markdown_reader "$temp_file" && return 0
            ;;
        epub)
            cmd_check epr epr && margin <(epr -d "$file" 2>/dev/null | sed '/^\s*$/d; /\[IMG:0\]/d; s/\[IMG:1\]//g') && return 0
            ;;
    esac

    cmd_check pandoc pandoc && margin <(pandoc -s -t plain -- "$file") && return 0
    cmd_check libreoffice libreoffice && libreoffice --headless --convert-to txt --outdir "${temp_dir}" "$file" >/dev/null 2>&1 &&
    margin "${temp_dir}"/*.txt && return 0 
    cmd_check -msg
}

nexttmp () {
	declare new="${TMPBOOKDIR}/books.$RANDOM"
	echo "$new"
}

nodash() {
	prog="$1"
	shift
	[[ "$1" == - ]] && shift
	$prog "$@"
}

handle_w3m() {
	if [[ "$1" == *\?* ]]; then
		t=$(nexttmp)
		ln -s "$1" "$t"
		set "$t" "$1"
	fi
	nodash "w3m -dump -T text/html" "$1"
}

_html2text() {
    nodash html2text "$1" "$2" | less -i &
    less_pid=$!
    wait "$less_pid" 
    return 0
}

ishtml() {
	[[ "$1" == - ]] && arg1=-stdin || arg1="$1"
	htmlopt=--unicode-snob
	cmd_check html2text python-html2text && html2text -utf8 </dev/null 2>/dev/null && htmlopt=-utf8
	# 3 lines following can easily be reshuffled according to the preferred tool
	cmd_check elinks elinks && margin <(nodash "elinks -dump -force-html" "$1" </dev/null 2>/dev/null) && return 0
	cmd_check w3m w3m && margin <(handle_w3m "$1" </dev/null 2>/dev/null) && return 0
	cmd_check lynx lynx && margin <(lynx -force_html -dump "$arg1" </dev/null 2>/dev/null) && return 0
	# different versions of html2text existingi, force unicode
	[[ "$1" == https://* ]] && return 0
	cmd_check html2text python-html2text && margin <(_html2text "$htmlopt" "$1" </dev/null 2>/dev/null) && return 0
    cmd_check -msg
}

imgview() {
    local file="$1"
    
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 1 ]] && cmd_check img2sixel libsixel &&
    img2sixel -w "${BOOKS_SIXEL_W:-1000}" -h "${BOOKS_SIXEL_H:-950}" "${file}" 2>/dev/null && return 0
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 2 ]] && [[ -n "$TERMUX_VERSION" ]] &&
    cmd_check viu viu && viu -w "${BOOKS_VIU_W:-63}" -h "${BOOKS_VIU_H:-25}" "${file}" 2>/dev/null && return 0
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 2 ]] && 
    cmd_check viu viu && viu -w "${BOOKS_VIU_W:-200}" -h "${BOOKS_VIU_H:-80}" "${file}" 2>/dev/null && return 0
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 3 ]] && [[ -n "$TERMUX_VERSION" ]] && 
    cmd_check catimg catimg && catimg -w "${BOOKS_CATIMG_W:-50}" "${file}" 2>/dev/null && return 0 
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 3 ]] && cmd_check catimg catimg &&
    catimg -w "${BOOKS_CATIMG_W:-150}" "${file}" 2>/dev/null && return 0 
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 4 ]] && [[ -n "$TERMUX_VERSION" ]] && 
    cmd_check chafa chafa && chafa -s "${BOOKS_CHAFA_S:-23}" "${file}" 2>/dev/null && return 0
    [[ -z "$BOOKS_IMG" || "$BOOKS_IMG" == 4 ]] && cmd_check chafa chafa &&
    chafa -s "${BOOKS_CHAFA_S:-70}" "${file}" 2>/dev/null && return 0

    cmd_check -msg
}

less_img() {
    IMAGE_DIR="$1"
    if [[ -d $IMAGE_DIR ]]; then
        images=("$IMAGE_DIR"/*)
    elif [[ -f $IMAGE_DIR ]]; then
        images=("$IMAGE_DIR")
    fi
    info_col="${INFO_COL:=\e[1;38;5;16;106m}"
    nc="\e[0m"
    index=0

    show_image() {
        imgview "${images[$index]}" 2>/dev/null
    }

    # Hide Curosr
    printf '\e[?25l'

    show_image

    # Disable echo for key presses
    stty -echo

    # Pagination loop
    while true; do
        total_page=${#images[@]}
        current_page=$((index + 1))
        printf '\e7\e[999H\e[K%b%s%b\e8' "$info_col" "Page: $current_page/$total_page | Up: up or w | Down: down or s | Quit: q" "$nc"

        read -rsn 1 key

        # Check if the key is an arrow (starts with \e)
        if [[ "$key" == $'\e' ]]; then
            read -rsn 2 -t 0.1 key2
            key="$key$key2"
        fi

        case "$key" in
            w|$'\e[A') # Up (previous image)
                if (( index > 0 )); then
                    ((index--))
                    show_image
                fi
                ;;
            s|$'\e[B') # Down (next image)
                if (( index < ${#images[@]} - 1 )); then
                    ((index++))
                    show_image
                fi
                ;;
            q|Q) # Quit
                # Re-enable echo for key presses
                stty echo
                clear
                # Show the cursor again
                printf '\e[?25h'
                break
                ;;
        esac
    done
}

pdfview() {
    local file="$1"
    temp_dir="${TMPBOOKDIR}/pdfview"
    temp_file="${temp_dir}/temp_file-%02d.jpg"
    [[ -d "$temp_dir" ]] && rm -rf "$temp_dir"
    [[ ! -d "$temp_dir" ]] && mkdir -p "$temp_dir"

    cmd_check pdftotext poppler && 
    pdf_lines=$(pdftotext -l 1 -nopgbrk -q -- "$file" - | wc -l) &&
    [[ "$pdf_lines" -gt 0 ]] &&
    margin <(pdftotext -layout -nopgbrk -q -- "$file" - 2>/dev/null) && return 0
    cmd_check mutool mupdf && margin <(mutool draw -F txt -i -- "${file}") && return 0 
    cmd_check magick imagemagick && 
    magick -- "${file}" -auto-orient -filter Box -resize "$resolution" -quality 85 "$temp_file" 2>/dev/null &&
    find "${temp_dir}" -maxdepth 1 -type f | read -r && less_img "$temp_dir" && return 0
    cmd_check -msg
}

podview() {
    local file="$1"
    cmd_check pod2text pod2text && margin <(pod2text "$file" 2>/dev/null) && return 0
    cmd_check perldoc perldoc && margin <(perldoc -T "$file" 2>/dev/null) && return 0
    cmd_check -msg
}

djvuview() {
    local file="$1"
    cmd_check djvutxt djvutxt && margin <(djvutxt "$file" 2>/dev/null) && return 0
    cmd_check -msg
}

psview() {
    local file="$1"
    cmd_check ps2ascii ghostscript && margin <(nodash ps2ascii "$file" 2>/dev/null) && return 0
    cmd_check -msg
}

dviview() {
    local file="$1"
    cmd_check dvi2tty dvi2tty && margin <(dvi2tty -q "$file") && return 0
    cmd_check -msg
}

xdg_open() {
    nohup xdg-open "$1" &>/dev/null &
    disown
}

# Function to select and open a book
select_book() {
    local book_path="$1"
    local resolution=${RESOLUTION:=2480x3508} # A4 Dimension
    
    if [[ -z "$book_path" ]]; then
        local list=()
        if [[ -n "$search_term" ]]; then
            list=("${filtered_books[@]}")
        else
            list=("${books_list[@]}")
        fi
        book_path="${list[$selected]}"
    fi
    
    ext_test="${book_path##*.}"
    ext_test="${ext_test,,}" # lowercase

    case "$ext_test" in
        txt)
            margin "$book_path" && return 0
            ;;
        md|markdown)
            if ! markdown_reader "$book_path"; then
                printf '\n\e[33mMarkdown file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        pod)
            if ! podview "$book_path"; then
                printf '\n\e[33mPOD file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        pdf)
            if ! pdfview "$book_path"; then
                printf '\n\e[33mPDF file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        png|jpg|jpeg)
            if ! less_img "$book_path"; then
                printf '\n\e[33mImage file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        rtf|odt|ods|odp|sxw|doc|docx|xls|xlsx|ipynb|epub|ppt|pptx|csv)
            if ! office_convert "$book_path"; then
                printf '\n\e[33mOffice file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        djvu)
            if ! djvuview "$book_path"; then
                printf '\n\e[33mDjvu file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        postscript|ps)
            if ! psview "$book_path"; then
                printf '\n\e[33mPS file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        dvi)
            if ! dviview "$book_path"; then
                printf '\n\e[33mDVI file: %s\e[m\n' "${book_path##*/}"
                return 1
            else
                return 0
            fi
            ;;
        htm|html|xhtml|xml)
            if ! ishtml "$book_path"; then
                printf '\n\e[33mWeb file: %s\e[m\n' "${book_path##*/}" 
                return 1
            else
                return 0
            fi
            ;;
        *)
            xdg_open "$book_path" && echo 'Unrecognized format' && exit 1
            ;;
        esac
}

# Check if a book was provided as an argument
if [[ -n "$1" ]]; then
    select_book "$1"
    exit 0
fi

# Interactive navigation
selected=0
esc=$'\e'
up=$'\e[A'
down=$'\e[B'
right=$'\e[C'
search_term=""
filtered_books=()

temp_search_results="${TMPBOOKDIR}/grep_search_results.txt"

while true; do
    clear
    stty -echo
    printf '\e[?25l'
    echo -e "\nUse ↑/↓ or w/s to navigate, Enter to select a book, 'f' to find by name, 'c' clear search, 'g' to grep content.\n"
    display_books "$search_term"
    echo -e "\nOr use 'q' to exit."

    IFS= read -rsn1 key  # Read first character

    if [[ "$key" == "$esc" ]]; then
        IFS= read -rsn2 rest
        key+="$rest"
    fi

    case "$key" in
        w|W|"$up")
            if [[ "$selected" -gt 0 ]]; then
                selected=$((selected - 1))
            fi
            ;;
        s|S|"$down")
            if [[ "$selected" -lt $((${#books_list[@]} - 1)) ]]; then
                selected=$((selected + 1))
            fi
            ;;
        f|F)
            stty echo
            echo -e "\nEnter search term: "
            read -r search_term

            # Busca os livros e armazena temporariamente em uma variável
            search_results=$(find "$books_folder" "$xdg_books_folder" -type f -iname "*${search_term}*" -print 2>/dev/null)

            # Verifica se há resultados
            if [[ -z "$search_results" ]]; then
                echo -e "\n${red}Book not found${nc}"
                sleep 1
                search_term=""  # Limpa o termo de pesquisa
                filtered_books=()  # Limpa o array de livros filtrados
            else
                # Se houver resultados, mapeia para o array filtered_books
                mapfile -t filtered_books <<< "$search_results"
                selected=0
            fi
            ;;
        g|G)
            stty echo
            echo -e "\nEnter content search term: "
            read -r search_term
            grep -irl "$search_term" "$books_folder" "$xdg_books_folder" > "$temp_search_results" 2>/dev/null
            mapfile -t filtered_books < "$temp_search_results"
            selected=0
            ;;
        ""|"$right")
            # Display the selected book with highlight
            if [[ -n "$search_term" ]]; then
                echo -e "$highlight You selected: ${filtered_books[$selected]} $nc"
            else
                echo -e "$highlight You selected: ${books_list[$selected]} $nc"
            fi
            select_book
            search_term=""
            ;;
        c|C)
            search_term=""
            ;;
        q|Q)
            reset
            exit 0
            ;;
        *)
            echo -e "\n${red}Invalid key!${nc}"
            sleep 1
            ;;
    esac
    [[ -t 1 ]] || exit 1
done

clear
