#!/usr/bin/env bash
# License: GPLv3
# Credits: Felipe Facundes

script="${HOME}/.shell_utils/scripts/calendar-hebrew.py"
py_venv="${HOME}/.python/calendar-hebrew"
activate="${py_venv}/bin/activate"

if [[ ! -d "$py_venv" ]]; then
    python -m venv "$py_venv"
    #shellcheck source=/dev/null
    source "$activate"
    export VIRTUAL_ENV="$py_venv"
    pip install convertdate holidays
fi

if [[ -z "$VIRTUAL_ENV" ]]; then
    export VIRTUAL_ENV="$py_venv"
    #shellcheck source=/dev/null
    source "$activate"
fi

"$script" "$@"