#!/usr/bin/env bash
# License: GPLv3
# Credits: Felipe Facundes
# Source: https://github.com/comfyanonymous/ComfyUI
# Tutorial: https://www.youtube.com/watch?v=TLE9NmN_sxw
#           https://youtu.be/xWUddF5oMb0

container="comfy"
docker_root="${HOME}/.dockers"
docker_base="${docker_root}/${container}"
docker_file="${docker_base}/Dockerfile"

# Function to display help menu
show_help() {
    cat << EOF

╔══════════════════════════════════════════════════════════════╗

╚══════════════════════════════════════════════════════════════╝

DESCRIPTION:
    This script automates the installation of ComfyUI CLI 

USAGE:
    ${0##*/} [OPTION]



EOF
    exit 0
}

create_docker_context() {
    echo "📁 Creating Docker build context..."
    [[ -f "$docker_file" ]] && return
    # Create Dockerfile
    cat > "$docker_file" << 'EOF'
FROM archlinux:latest

# Atualiza o sistema e instala pacotes essenciais
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm sudo wget base libsm libxext libxrender mesa clinfo pkgconf libxrandr libxinerama \
    libxi libxcursor libglvnd pciutils ocl-icd base-devel python python-pip python-pipx git zsh && \
    pacman -Scc --noconfirm

# Cria usuário comfy com todas as permissões
RUN useradd -m -G wheel -s /bin/zsh comfy && \
    echo "comfy:123" | chpasswd && \
    echo "comfy ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/comfy && \
    chmod 0440 /etc/sudoers.d/comfy

# Configurações adicionais para o usuário comfy
USER comfy
WORKDIR /home/comfy

# Configura o pipx
ENV PATH="/home/comfy/.local/bin:${PATH}"
RUN pipx ensurepath && \
    echo 'export PATH="/home/comfy/.local/bin:$PATH"' >> /home/comfy/.zshrc

# Instala a framework shell_utils
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/felipefacundes/shell_utils/refs/heads/main/install.sh)"

RUN /home/comfy/.shell_utils/scripts/comfy-cli -nu

# Mantém o container em execução com ZSH
CMD ["/bin/zsh"]
EOF
}

if [[ ! -d "$docker_base" ]]; then
    mkdir -p "$docker_base"
    create_docker_context
    docker build -t "$container" -f "$docker_file" "$docker_base"
fi

if docker images | grep -q archlinux; then
    docker start "$container" && docker exec -it "$container" zsh
fi
