#!/bin/bash
# License: GPLv3
# Credits: Felipe Facundes

# A simple documentation reader for Shell_utils Shell Scripts.

if [[ -z $1 ]]; then
    echo "Usage: ${0##*/} script"
    exit 1
fi

awk '
BEGIN { inside_block = 0 }

# Check the beginning of the DOCUMENTATION block
/: <<'\''DOCUMENTATION'\''/ { inside_block = 1; next }

# Check the end of the DOCUMENTATION block
inside_block && $0 == "DOCUMENTATION" { inside_block = 0; exit }

# Print lines within the DOCUMENTATION block
inside_block { print }
' "$1"