#!/bin/bash

: <<'DOCUMENTATION'
__NV_PRIME_RENDER_OFFLOAD=1
DOCUMENTATION

if [ -z "${1}" ]; then
    echo "Usage: ${0##*/} command"
else
    __NV_PRIME_RENDER_OFFLOAD=1
    __VK_LAYER_NV_optimus=NVIDIA_only
    __GLX_VENDOR_LIBRARY_NAME=nvidia "${@}"
fi