#!/usr/bin/env bash
# License: GPLv3
# Credits: Felipe Facundes

: <<'DOCUMENTATION'
A utility to facilitate the use of the TAR command
DOCUMENTATION

file="$1"

if [[ -z "$1" ]]; then
	echo "${0##*/} file or directory"
	echo "Or"
    echo 'tar -cf file_name.tar file_or_dir'
else
    tar -cf "${file%.*}.tar" "$file"
fi