#!/usr/bin/env bash
######### Openbox Shortcut Help #########

if command -v ccat >/dev/null 2>&1 ; then
    ccat --color=always ~/.config/openbox/rc.xml | less -i -R -N --use-color --color=HBCEMNPRSWsu
else
    cat --color=always ~/.config/openbox/rc.xml | less -i -R -N --use-color --color=HBCEMNPRSWsu
fi