#!/usr/bin/env bash
######### Wayfire Shortcut Help #########

if command -v ccat >/dev/null 2>&1 ; then
    ccat --color=always ~/.config/wayfire.ini | less -i -R -N --use-color --color=HBCEMNPRSWsu
else
    cat --color=always ~/.config/wayfire.ini | less -i -R -N --use-color --color=HBCEMNPRSWsu
fi