#!/usr/bin/env bash

markdown_reader() {
	~/.shell_utils/scripts/markdown-reader -nc -nf
}

en_us() {
	cat <<-'EOF'
	## First, list all available video outputs and the connected monitors using the command:
	`$ xrandr`

	## CVT generates a model line based on the resolution and update rate you want. 
	## For example, to create a mode of 1920x1080 to 75 Hz, run:
	`$ cvt 1920 1080 75`

	## Output of CVT
	##### # 1920x1080 74.96 Hz (CVT 2.07M9) hsync: 83.85 kHz; pclk: 220.75 MHz
	`Modeline "1920x1080_75.00"  220.75  1920 2056 2256 2592  1080 1083 1088 1129 -hsync +vsync`

	## Copy the generated model line (the second line).
	## Use the previously copied model line:
	`$ xrandr --newmode "1920x1080_75.00"  220.75  1920 2056 2256 2592  1080 1083 1088 1129 -hsync +vsync`

	## Add mode to the desired monitor. For example, to add to HDMI-0:
	`$ xrandr --addmode HDMI-0 1920x1080_75.00`

	## Now apply video mode to the desired monitor. For example, to apply to HDMI-0:
	`$ xrandr --output HDMI-0 --mode 1920x1080_75.00 --rate 75`
	EOF
}

pt_br() {
    cat <<-'EOF'
	## Primeiro, liste todas as saídas de vídeo disponíveis e os monitores conectados usando o comando:
	`$ xrandr`

	## O CVT gera uma linha de modelo com base na resolução e taxa de atualização desejadas.
	## Por exemplo, para criar um modo de 1920x1080 a 75 Hz, execute:
	`$ cvt 1920 1080 75`

	## Saída do CVT
	##### # 1920x1080 74.96 Hz (CVT 2.07M9) hsync: 83.85 kHz; pclk: 220.75 MHz
	`Modeline "1920x1080_75.00"  220.75  1920 2056 2256 2592  1080 1083 1088 1129 -hsync +vsync`

	## Copie a linha de modelo gerada (a segunda linha).
	## Use a linha de modelo copiada anteriormente:
	`$ xrandr --newmode "1920x1080_75.00"  220.75  1920 2056 2256 2592  1080 1083 1088 1129 -hsync +vsync`

	## Adicione o modo ao monitor desejado. Por exemplo, para adicionar ao HDMI-0:
	`$ xrandr --addmode HDMI-0 1920x1080_75.00`

	## Agora aplique o modo de vídeo ao monitor desejado. Por exemplo, para aplicar ao HDMI-0:
	`$ xrandr --output HDMI-0 --mode 1920x1080_75.00 --rate 75`
	EOF
}

es_es() {
	cat <<-'EOF'
	## Primero, lista todas las salidas de video disponibles y los monitores conectados usando el comando:
	`$ xrandr`

	## CVT genera una línea de modelo basada en la resolución y la tasa de actualización que deseas.
	## Por ejemplo, para crear un modo de 1920x1080 a 75 Hz, ejecuta:
	`$ cvt 1920 1080 75`

	## Salida de CVT
	##### # 1920x1080 74.96 Hz (CVT 2.07M9) hsync: 83.85 kHz; pclk: 220.75 MHz
	`Modeline "1920x1080_75.00"  220.75  1920 2056 2256 2592  1080 1083 1088 1129 -hsync +vsync`

	## Copia la línea de modelo generada (la segunda línea).
	## Usa la línea de modelo copiada anteriormente:
	`$ xrandr --newmode "1920x1080_75.00"  220.75  1920 2056 2256 2592  1080 1083 1088 1129 -hsync +vsync`

	## Agrega el modo al monitor deseado. Por ejemplo, para agregar a HDMI-0:
	`$ xrandr --addmode HDMI-0 1920x1080_75.00`

	## Ahora aplica el modo de video al monitor deseado. Por ejemplo, para aplicar a HDMI-0:
	`$ xrandr --output HDMI-0 --mode 1920x1080_75.00 --rate 75`
	EOF
}

if [[ "${LANG,,}" =~ pt_ ]]; then
	cmd="pt_br"
elif [[ "${LANG,,}" =~ es_ ]]; then
	cmd="es_es"
else
	cmd="en_us"
fi

"$cmd" | markdown_reader